<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DeviceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('devices')->insert([
            [
                'device_name' => 'Router A',
                'brand_and_type' => 'Cisco 2901',
                'serial_number' => 'SN123456789',
                'device_type' => 'Router',
                'ip_address' => '192.168.1.1',
                'tag_name' => 'RTR-001',
                'location' => 'Data Center 1',
                'contract_id' => 1,
                'installation_year' => '2019',
                'description' => 'Main branch router',
                'user_responsible' => 'John Doe',
                'user_device' => 'Network Team',
                'condition' => 'Good',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Switch B',
                'brand_and_type' => 'HP ProCurve 2920',
                'serial_number' => 'SN987654321',
                'device_type' => 'Switch',
                'ip_address' => '192.168.1.2',
                'tag_name' => 'SWT-002',
                'location' => 'Data Center 2',
                'contract_id' => 2,
                'installation_year' => '2020',
                'description' => 'Core switch for VLAN segmentation',
                'user_responsible' => 'Jane Smith',
                'user_device' => 'IT Support',
                'condition' => 'Good',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Firewall C',
                'brand_and_type' => 'Fortinet FG-100E',
                'serial_number' => 'SN1122334455',
                'device_type' => 'Firewall',
                'ip_address' => '192.168.1.3',
                'tag_name' => 'FW-003',
                'location' => 'Data Center 1',
                'contract_id' => 3,
                'installation_year' => '2021',
                'description' => 'Security firewall',
                'user_responsible' => 'Michael Brown',
                'user_device' => 'Security Team',
                'condition' => 'Excellent',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Access Point D',
                'brand_and_type' => 'Ubiquiti UAP-AC-PRO',
                'serial_number' => 'SN4455667788',
                'device_type' => 'Access Point',
                'ip_address' => '192.168.1.4',
                'tag_name' => 'AP-004',
                'location' => 'Office Floor 1',
                'contract_id' => 4,
                'installation_year' => '2018',
                'description' => 'WiFi access point',
                'user_responsible' => 'Sarah Johnson',
                'user_device' => 'Networking',
                'condition' => 'Fair',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Server E',
                'brand_and_type' => 'Dell PowerEdge R740',
                'serial_number' => 'SN5566778899',
                'device_type' => 'Server',
                'ip_address' => '192.168.1.5',
                'tag_name' => 'SRV-005',
                'location' => 'Data Center 3',
                'contract_id' => 5,
                'installation_year' => '2022',
                'description' => 'Primary application server',
                'user_responsible' => 'Robert Wilson',
                'user_device' => 'IT Operations',
                'condition' => 'New',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Printer F',
                'brand_and_type' => 'HP LaserJet 4200',
                'serial_number' => 'SN9988776655',
                'device_type' => 'Printer',
                'ip_address' => '192.168.1.6',
                'tag_name' => 'PRN-006',
                'location' => 'Office Floor 2',
                'contract_id' => 6,
                'installation_year' => '2017',
                'description' => 'Shared office printer',
                'user_responsible' => 'Alice Davis',
                'user_device' => 'General Staff',
                'condition' => 'Good',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Workstation G',
                'brand_and_type' => 'Lenovo ThinkPad P53',
                'serial_number' => 'SN2233445566',
                'device_type' => 'Workstation',
                'ip_address' => '192.168.1.7',
                'tag_name' => 'WS-007',
                'location' => 'Engineering Lab',
                'contract_id' => 7,
                'installation_year' => '2023',
                'description' => 'High-performance workstation',
                'user_responsible' => 'David Lee',
                'user_device' => 'Engineering Team',
                'condition' => 'New',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'NAS H',
                'brand_and_type' => 'Synology DS920+',
                'serial_number' => 'SN6677889900',
                'device_type' => 'Storage',
                'ip_address' => '192.168.1.8',
                'tag_name' => 'NAS-008',
                'location' => 'Server Room',
                'contract_id' => 8,
                'installation_year' => '2016',
                'description' => 'Network attached storage',
                'user_responsible' => 'Emma Clark',
                'user_device' => 'Storage Team',
                'condition' => 'Good',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'UPS I',
                'brand_and_type' => 'APC Smart-UPS 1500',
                'serial_number' => 'SN8899001122',
                'device_type' => 'Power Backup',
                'ip_address' => '192.168.1.9',
                'tag_name' => 'UPS-009',
                'location' => 'Data Center 1',
                'contract_id' => 9,
                'installation_year' => '2015',
                'description' => 'Power backup system',
                'user_responsible' => 'Oliver White',
                'user_device' => 'Facilities',
                'condition' => 'Fair',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'device_name' => 'Camera J',
                'brand_and_type' => 'Hikvision DS-2CD2142FWD-I',
                'serial_number' => 'SN1122446688',
                'device_type' => 'CCTV',
                'ip_address' => '192.168.1.10',
                'tag_name' => 'CCTV-010',
                'location' => 'Entrance Gate',
                'contract_id' => 10,
                'installation_year' => '2020',
                'description' => 'Security surveillance camera',
                'user_responsible' => 'Sophia Martinez',
                'user_device' => 'Security Team',
                'condition' => 'Excellent',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
